### ISSUE TITLE
Error when i try to import module

### ISSUE THREAD

**Issue by TristxnB** [Moxio/js-struct-compare#2]
Hi ! 
I get this error when i try to import the module : 
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

**Comment by aboks** [comment]
This library is written to be consumed as an ES Module only. If you're writing for a Node.js context, you could use the `--experimental-modules` flag in Node.js version 12 and higher. See https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff for more details. If that's not an option, you could use https://github.com/standard-things/esm to load ES Modules from a CommonJS context. If I recall correctly, that should look something like the following:

```js
const requireESM = require("esm")(module);
const compare = requireESM("js-struct-compare").default;
```

Let me know if this solves your problem.

**Comment by TristxnB** [comment]
Hi ! I can't use the first solution so i used the second one. It works !
Thanks :)

**Comment by aboks** [comment]
Great, good to hear!
